### PR TITLE
Update it-national.php

### PR DESCRIPTION
**Pull request by sabas**
The 17/3 holiday was testing true for this year, I changed the syntax.

### CODE REVIEW

**Comment by kylekatarnls** [comment]
I added a unit test to confirm the bug: #46 and will pull your branch in this PR to test it actually fix it.

**Comment by kylekatarnls** [comment]
PS: Nice to see a Guybrush Threepwood avatar, this make 2 LucasArt characters in the topic.

**Comment by kylekatarnls** [comment]
According to the unit tests is sounds like 2011-03-17 is no longer an holiday with this modification.

**Comment by sabas** [comment]
Mighty pirate :tm: 

Should be a closure instead? It's the only example I found for a single year celebration

**Comment by kylekatarnls** [comment]
Great idea, it's working. I will inspect why other syntaxes were failing.

**Pull request merged**
